import Head from 'next/head'
import Image from 'next/image'
// import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import record from '../data/genshin_characters.json'
import { useState } from 'react'

// const inter = Inter({ subsets: ['latin'] })

export default function Characters() {

    return (
        <>
            <Head>
                <title>Wish Impact Characters</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>

                {
                    record.map((rec, index) => {
                        return (
                            <>
                                <>{rec.vision == "Anemo" ? <div key={index}>
                                    <div>{rec.character_name}</div>
                                    <div>{rec.rarity}</div>
                                    <div>{rec.vision}</div> </div> : <></>}</>
                            </>
                        )
                    })
                }

            </main>
        </>
    )
}
