import Head from 'next/head'
import Image from 'next/image'
// import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import record from '../data/genshin_characters.json'
import { useState, useEffect } from 'react'

// const inter = Inter({ subsets: ['latin'] })


export default function Home() {
  const [randomChar, setRandomChar] = useState(0)

  const giveRandomCharacter = () => {
    const randomChar = Math.floor(Math.random() * record.length);
    setRandomChar(randomChar)

    let wishReveal = document.getElementById("charDiv");
    wishReveal.style.display = "block"
  }

  const [loading, setLoading] = useState(true);
  useEffect(() => {
    const timer = setTimeout(() => {
      setLoading(false);
    }, 5000);
    return () => clearTimeout(timer);
  }, []);

  if (loading) {
    return (<div>
      // put loading comp here!
    </div>);
  }

  return (
    <>
      <Head>
        <title>Wish Impact </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>

          <div>
            <div id="charDiv" style={{ display: "none" }}>
              {record[randomChar].character_name}
              <Image src={record[randomChar].image_url} width={400} height={400}></Image>
            </div>

            <div>
              <button onClick={giveRandomCharacter}>Next</button>
            </div>
          </div>

        </div>
      </main>
    </>
  )
}
